apiVersion: v1
kind: Namespace
metadata:
  name: valuecanvas
  labels:
    name: valuecanvas
    environment: production
    istio-injection: enabled
  annotations:
    security.istio.io/tlsMode: istio
