apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: valuecanvas-staging

bases:
  - ../../base

nameSuffix: -staging

commonLabels:
  environment: staging

patches:
  - path: deployment-patch.yaml

replicas:
  - name: backend
    count: 1
  - name: frontend
    count: 1

images:
  - name: REGISTRY_URL/valuecanvas-backend
    newTag: develop
  - name: REGISTRY_URL/valuecanvas-frontend
    newTag: develop

configMapGenerator:
  - name: valuecanvas-config
    behavior: merge
    literals:
      - node-env=staging
      - log-level=debug
